remote_theme: pages-themes/cayman@v0.2.0
title: "SirBarbaffo's lair of sleep deprivation."
description: The title is a work in progess.
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
